name: Add dependency PRs to board

on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Dry run mode'
        required: false
        type: boolean
        default: true
    secrets:
      github-token:
        description: 'GitHub token with repo access'
        required: true

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add pull requests to project
    runs-on: ubuntu-latest
    steps:
      - uses: stairwaytowonderland/add-to-project@v1
        with:
          dry-run: ${{ inputs.dry-run }}
          all-by-project-owner: true
          project-url: https://github.com/orgs/${{ github.repository_owner }}/projects/5
          github-token: ${{ secrets.github-token }}
          labeled: dependencies
