# This workflow will lint the entire codebase using the
# `super-linter/super-linter` action.
#
# For more information, see the super-linter repository:
#     https://github.com/super-linter/super-linter
name: Lint Codebase

on:
  workflow_call:
    inputs:
      node-cache-key:
        description: 'The Node.js cache key to use.'
        type: string
        default: 'npm'
      checkov-file-name:
        description: 'The Checkov config file to use.'
        type: string
        default: '.checkov.yml'
      node-version-file:
        description: 'The Node.js version file to use.'
        type: string
        default: '.node-version'
      superlinter-filter-regex-exclude:
        description: 'The regex pattern to exclude files from the super-linter.'
        type: string
        default: '(dist/.*|.*\.csv$)'
      superlinter-rules-path:
        description: 'The path to the super-linter rules.'
        type: string
        default: /
      superlinter-validate-editorconfig:
        description: 'Whether to validate editorconfig files with the super-linter.'
        type: boolean
        default: true
      superlinter-validate-prettier:
        description: 'Whether to validate TypeScript files with Prettier using the super-linter.'
        type: boolean
        default: true
      superlinter-validate-checkov:
        description: 'Whether to validate Checkov with the super-linter.'
        type: boolean
        default: false
      superlinter-validate-natural-language:
        description: 'Whether to validate natural language files with the super-linter.'
        type: boolean
        default: false
      additional-vars:
        required: false
        type: string

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Export AdditionalEnvironment Variables
        if: ${{ inputs.additional-vars != '' }}
        env:
          RAW_VARS: ${{ inputs.additional-vars }}
        run: |
          # Read line-by-line to preserve values with spaces or special signs safely
          echo "$RAW_VARS" | while IFS= read -r line || [ -n "$line" ]; do
            # Skip empty lines
            if [ -n "$line" ]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done

      - name: Check if Node.js Version is Specified
        id: check-if-node
        env:
          NODE_VERSION_FILE: ${{ inputs.node-version-file }}
        run: |
          if [ -f "$NODE_VERSION_FILE" ]; then
            echo "Node.js version file found: $NODE_VERSION_FILE"
            echo "setup-node=true" >> $GITHUB_OUTPUT
          else
            echo "Node.js version file not found: $NODE_VERSION_FILE"
            echo "setup-node=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        id: setup-node
        if: steps.check-if-node.outputs.setup-node == 'true'
        uses: actions/setup-node@v7
        with:
          node-version-file: ${{ inputs.node-version-file }}
          cache: ${{ inputs.node-cache-key }}

      - name: Install Dependencies
        id: install
        if: steps.check-if-node.outputs.setup-node == 'true'
        run: npm ci

      - name: Copy Linter Rules
        if: steps.check-if-node.outputs.setup-node == 'true'
        env:
          SUPERLINTER_RULES_PATH: ${{ inputs.superlinter-rules-path }}
          GITHUB_LINTER_RULES_PATH: .github/linters
        run: |
          old_dir="${GITHUB_WORKSPACE%/}"
          new_workspace="${GITHUB_WORKSPACE%/}/${SUPERLINTER_RULES_PATH%/}"
          new_dir="${new_workspace%/}/${GITHUB_LINTER_RULES_PATH%/}"
          if [ ! -d "${new_dir}" ]; then
            mkdir -p "${new_dir}"
          fi
          cp "${old_dir}/".prettier* "${new_dir}/"
          echo "Copied linter rules from '${old_dir}' to '${new_dir}'"
          ls -la "${new_dir}"

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter@v8
        env:
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true # default: true
          SAVE_SUPER_LINTER_SUMMARY: true # default: false
          CHECKOV_FILE_NAME: ${{ inputs.checkov-file-name }}
          DEFAULT_BRANCH: ${{ github.repository.default_branch }}
          FILTER_REGEX_EXCLUDE: ${{ inputs.superlinter-filter-regex-exclude }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ${{ inputs.superlinter-rules-path }}
          VALIDATE_PRETTIER: ${{ inputs.superlinter-validate-prettier }}
          VALIDATE_EDITORCONFIG: ${{ inputs.superlinter-validate-editorconfig }}
          VALIDATE_CHECKOV: ${{ inputs.superlinter-validate-checkov }}
          VALIDATE_NATURAL_LANGUAGE: ${{ inputs.superlinter-validate-natural-language }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JSCPD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_JSON: false

          # Force Super-Linter to write out the raw Prettier error diff logs
          CREATE_LOG_FILE: true

      # This step will only execute if Super-Linter fails, printing the exact diff
      - name: Print Super-Linter Prettier Diff
        if: failure()
        run: |
          if [ -f "super-linter.log" ]; then
            cat super-linter.log
          fi

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        if: ! inputs.superlinter-validate-checkov
        with:
          config_file: ${{ inputs.checkov-file-name }}
