# This workflow will lint the entire codebase using the
# `super-linter/super-linter` action.
#
# For more information, see the super-linter repository:
#     https://github.com/super-linter/super-linter
name: Lint Codebase

on:
  workflow_call:
    inputs:
      node-cache-key:
        description: 'The Node.js cache key to use.'
        type: string
        default: 'npm'
      checkov-file-name:
        description: 'The Checkov config file to use.'
        type: string
        default: '.checkov.yml'
      node-version-file:
        description: 'The Node.js version file to use.'
        type: string
        default: '.node-version'
      superlinter-filter-regex-exclude:
        description: 'The regex pattern to exclude files from the super-linter.'
        type: string
        default: '(dist/.*|.*\.csv$)'
      superlinter-rules-path:
        description: 'The path to the super-linter rules.'
        type: string
        default: .
      superlinter-validate-prettier:
        description: 'Whether to validate TypeScript files with Prettier using the super-linter.'
        type: boolean
        default: true
      superlinter-validate-editorconfig:
        description: 'Whether to validate editorconfig files with the super-linter.'
        type: boolean
        default: true
      superlinter-validate-checkov:
        description: 'Whether to validate Checkov with the super-linter.'
        type: boolean
        default: false
      superlinter-validate-natural-language:
        description: 'Whether to validate natural language files with the super-linter.'
        type: boolean
        default: false

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v8
        env:
          CHECKOV_FILE_NAME: ${{ inputs.checkov-file-name }}
          DEFAULT_BRANCH: ${{ github.repository.default_branch }}
          FILTER_REGEX_EXCLUDE: ${{ inputs.superlinter-filter-regex-exclude }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ${{ inputs.superlinter-rules-path }}
          VALIDATE_PRETTIER: ${{ inputs.superlinter-validate-prettier }}
          VALIDATE_EDITORCONFIG: ${{ inputs.superlinter-validate-editorconfig }}
          VALIDATE_CHECKOV: ${{ inputs.superlinter-validate-checkov }}
          VALIDATE_NATURAL_LANGUAGE: ${{ inputs.superlinter-validate-natural-language }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JSCPD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_JSON: false

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        if: ! inputs.superlinter-validate-checkov
        with:
          config_file: ${{ inputs.checkov-file-name }}
