# In TypeScript actions, `dist/` is a special directory. When you reference
# an action with the `uses:` property, `dist/index.js` is the code that will be
# run. For this project, the `dist/index.js` file is transpiled from other
# source files. This workflow ensures the `dist/` directory contains the
# expected transpiled code.
#
# If this workflow is run from a feature branch, it will act as an additional CI
# check and fail if the checked-in `dist/` directory does not match what is
# expected from the build.
name: NPM - Check Transpiled JavaScript

on:
  workflow_call:
    inputs:
      build-command:
        description: 'The build command to run.'
        type: string
        default: |
          npm run bundle
      dist-dir:
        description: 'The dist/ directory to check.'
        type: string
        default: 'dist'
      files-to-ignore:
        description: 'A pipe-separated array of files to ignore when comparing the expected and actual dist/ directories.'
        type: string
        default: 'index.js.map|sourcemap-register.js|licensed.txt'
      node-cache-key:
        description: 'The Node.js cache key to use.'
        type: string
        default: 'npm'
      node-version-file:
        description: 'The Node.js version file to use.'
        type: string
        default: '.node-version'

permissions:
  contents: read

jobs:
  check-dist:
    name: Check dist/
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v7
        with:
          node-version-file: ${{ inputs.node-version-file }}
          cache: ${{ inputs.node-cache-key }}

      - name: Remove dist/ Directory
        id: remove-dist
        env:
          DIST_DIR: ${{ inputs.dist-dir }}
        run: npx rimraf ${DIST_DIR}

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Build dist/ Directory
        id: build
        run: ${{ inputs.build-command }}

      # This will fail the workflow if the `dist/` directory is different than
      # expected.
      - name: Compare Directories
        id: diff
        env:
          DIST_DIR: ${{ inputs.dist-dir }}
          FILES_TO_IGNORE: ${{ inputs.files-to-ignore }}
        run: |
          # Get a list of files that are different between the checked-in dist/ directory and the generated dist/ directory,
          # then trim the list to remove any leading or trailing whitespace.
          CHANGED_FILES=$(git diff --ignore-space-at-eol --name-only "${DIST_DIR}" | grep -vE "$FILES_TO_IGNORE" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
          if [ -n "$CHANGED_FILES" ]; then
            echo "❗️ Detected uncommitted changes after build (see diff output below)." >&2
            echo "This indicates that the dist/ directory ("${DIST_DIR}") is out of sync with the checked-in index.js." >&2
            echo "⭐️ If the changes below are expected, run 'npm run build:compile && npm run build:package' and commit the output files." >&2
            # Run `git diff` for each line/file in $CHANGED_FILES:
            echo "$CHANGED_FILES" | xargs -I {} git diff --ignore-space-at-eol --text -- {}
            exit 1
          else
            echo "✅ No uncommitted changes detected after build."
          fi

      # If `dist/` was different than expected, upload the expected version as a
      # workflow artifact.
      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
        name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: ${{ inputs.dist-dir }}/
